// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdtgwzxsofoskhcvsbdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkdGd3enhzb2Zvc2toY3ZzYmRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyODkwMDQsImV4cCI6MjA3NDg2NTAwNH0.8I7izCSBGh19LL1wUMbXL-f3B_dxK2IoIFrWJL6k9tM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
    }
});